name: Deploy Next.js App

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main # Trigger deployment for pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Set the version of pnpm to use

      # Step 3: Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 4: Lint the code
      - name: Lint
        run: pnpm run lint

      # Step 5: Build the project
      - name: Build
        run: pnpm run build

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: "--prod"
